name: Action Test

on: 
  issues:
    types: 
      - labeled

jobs:
  label:
    
    runs-on: ubuntu-latest
    name: Add label to Issue if it is secure
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # load and run local action
        if: github.event.label.name == 'testing'
        name: Label an issue
        with:
          rqcode-token: ${{ secrets.RQCODE_TOKEN }}
          platform: canonical_ubuntu_18.04_lts
          username: ${{ secrets.ARQAN_USER }}
          password: ${{ secrets.ARQAN_PASS }}
          create-issues: 'true'
